route:
  receiver: default
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 4h

receivers:
  - name: default
    email_configs:
      - to: "test@example.com"
        from: "monitor@example.com"
        smarthost: "mailhog:1025"
        require_tls: false
    webhook_configs:
      - url: "http://example.com/alert-webhook"

inhibit_rules:
  - source_matchers:
      - severity = critical
    target_matchers:
      - severity = warning
    equal: ["alertname"]

